language: ruby
rvm:
  - 2.2.2
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - mysql -e 'create database collage_test'
