default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: collage-dev
test:
  <<: *default
  database: collage-test

production:
  <<: *default
  database: collage-production
